GET http://localhost:8080

###
GET http://localhost:8080/api

###
GET http://localhost:8080/api/search?nameen=China

###

POST http://localhost:8080/api/save
Content-Type: application/json

{
  "Avatar": "www.google.com",
  "NameZh": "谷歌",
  "NameEn": "Google"
}
###

POST http://localhost:8080/api/delete
Content-Type: application/json

{
  "Id":8
}
###